export const TRIP_CREATION_CANCELED = 'TRIPS.NEW.TRIP_CREATION_CANCELED';
export const CHAPTER_CREATION_STARTED = 'TRIPS.NEW.CHAPTER_CREATION_STARTED';
export const TRIP_SAVED = 'TRIPS.NEW.TRIP_SAVED';
export const TAB_CHANGED = 'TRIPS.NEW.TAB_CHANGED';