export const CHAPTER_LOCATION_CHANGED = 'TRIPS.NEW.CHAPTER_LOCATION_CHANGED';
export const CHAPTER_DATES_CHANGED = 'TRIPS.NEW.CHAPTER_DATES_CHANGED';
export const TRIP_CREATION_CANCELED = 'TRIPS.NEW.TRIP_CREATION_CANCELED';
export const TRIP_SAVED = 'TRIPS.NEW.TRIP_SAVED';
export const TAB_CHANGED = 'TRIPS.NEW.TAB_CHANGED';
export const CHAPTER_SUMMARY_CHANGED = 'TRIPS.NEW.CHAPTER_SUMMARY_CHANGED';