export const CHAPTER_LOCATION_CHANGED = 'TRIPS.NEW.CHAPTER_LOCATION_CHANGED';
export const TRIP_CREATION_CANCELED = 'TRIPS.NEW.TRIP_CREATION_CANCELED';
export const TRIP_SAVED = 'TRIPS.NEW.TRIP_SAVED';